name: Node CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USER }}
       key: ${{ secrets.UBUNTU_KEY }}
       script: |
         echo "Connected successfully"
         cd /home/ubuntu/your-repo-name
         git pull origin master
